version: '3.8'
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Your NGINX configuration
  #     - /etc/ssl/certs:/etc/ssl/certs:ro  # Mount the SSL certs directory
  #   depends_on:
  #     - frontend
  #     - backend
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6351:6333
      - 6352:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./databases/qdrant/snapshots:/qdrant/snapshots
      - ./qdrant_data:/qdrant/storage
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: database
    build:
      context: ./databases/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
  backend:
    container_name: server
    build: ./server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - qdrant
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - QUIZ_MODEL=${QUIZ_MODEL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - NOREPLY_EMAIL=${NOREPLY_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./data:/usr/src/app/data
      - ./databases/qdrant/snapshots:/qdrant/snapshots
  frontend:
    container_name: client
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:80"


