version: "3.8"

volumes:
  postgres_data:
  qdrant_data:
  qdrant_snapshots:
  backend_data:

services:
  db:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - 6351:6333
      - 6352:6334
    volumes:
      - qdrant_snapshots:/qdrant/snapshots
      - qdrant_data:/qdrant/storage
    depends_on:
      - db

  backend:
    container_name: server
    image: ghcr.io/melzak252/countrydle-backend:latest
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
      - qdrant
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - QUIZ_MODEL=${QUIZ_MODEL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - NOREPLY_EMAIL=${NOREPLY_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - backend_data:/usr/src/app/data
      - qdrant_snapshots:/qdrant/snapshots

  frontend:
    container_name: client
    image: ghcr.io/melzak252/countrydle-frontend:latest
    restart: always
    ports:
      - "8083:5173"
    depends_on:
      - backend